# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('annotation', models.CharField(default='请注意避免赛程时间冲突', max_length=25, verbose_name='注释')),
                ('race_name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='赛程名字')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='赛程开始日期')),
                ('last', models.IntegerField(default=3, verbose_name='此赛程持续时间')),
            ],
            options={
                'verbose_name_plural': '赛程',
                'ordering': ['start'],
            },
        ),
    ]
