# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process_handle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='赛程开始日期'),
        ),
    ]
