# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process_handle', '0002_auto_20190414_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='last',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='赛程结束时间'),
        ),
    ]
