# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('process_handle', '0003_auto_20190414_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_sum_score', models.IntegerField(default=0, verbose_name='最高总分')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_handle.Schedule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
            ],
            options={
                'verbose_name_plural': '一个赛程某个队伍的最高总分(用于创建榜单)',
            },
        ),
    ]
