# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='文件ID')),
                ('submitter_id', models.CharField(max_length=20, verbose_name='提交人ID')),
                ('status', models.BooleanField()),
                ('file_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9, verbose_name='学号')),
                ('team_id', models.CharField(max_length=20, verbose_name='队伍ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=20, verbose_name='文件ID')),
                ('team_id', models.CharField(max_length=20, verbose_name='队伍ID')),
            ],
        ),
    ]
