# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-18 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=10, verbose_name='学校')),
                ('student_id', models.CharField(max_length=15, verbose_name='学号')),
                ('phone', models.CharField(max_length=12, verbose_name='联系电话')),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
