# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecomq',
            name='ma_sc_dat',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最高分时间'),
        ),
    ]
