# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190216_2320'),
        ('kaggle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='题目标题')),
                ('content', models.TextField(max_length=1500, verbose_name='题目内容')),
            ],
            options={
                'verbose_name_plural': '竞赛题目',
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_called_name', models.CharField(max_length=30, verbose_name='页面显示文件名')),
                ('comquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaggle.ComQuestion')),
            ],
            options={
                'verbose_name_plural': '赛题对应源文件',
            },
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='文件得分')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='系统计算过得分')),
                ('comquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaggle.ComQuestion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
            ],
            options={
                'verbose_name_plural': '队伍提交的文件',
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='TeamComposition',
        ),
        migrations.DeleteModel(
            name='TeamSubmit',
        ),
    ]
