# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0002_auto_20190414_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comquestion',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='题目内容'),
        ),
    ]
