# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0002_auto_20190219_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitfile',
            name='submitfile',
            field=models.FileField(default='submit/default.png', upload_to='submit/'),
        ),
    ]
