# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0003_submitfile_submitfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfile',
            name='submitfile',
            field=models.FileField(default='submit/default.png', upload_to='submit/%Y/%m/%d'),
        ),
    ]
