# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0004_auto_20190224_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='sourcefile',
            field=models.FileField(default='source/default.png', upload_to='source/'),
        ),
    ]
