# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0005_sourcefile_sourcefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file_called_name',
            field=models.CharField(max_length=30, verbose_name='页面显示文件名(文件名+扩展名)'),
        ),
    ]
