# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-05 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190305_2115'),
        ('kaggle', '0008_auto_20190305_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreComq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.FloatField(default=0, verbose_name='最高分')),
                ('last_score', models.FloatField(default=0, verbose_name='最新分数')),
                ('ma_sc_dat', models.DateField(default=django.utils.timezone.now, verbose_name='最高分日期')),
                ('comquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaggle.ComQuestion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='stdanswer',
            name='comquestion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kaggle.ComQuestion'),
        ),
    ]
