# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0009_auto_20190305_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecomq',
            name='ma_sc_dat',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='最高分日期'),
        ),
    ]
