# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0010_auto_20190305_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecomq',
            name='ma_sc_dat',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='最高分日期'),
        ),
    ]
