# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-06 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0011_auto_20190305_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecomq',
            options={'verbose_name_plural': '某个队伍对应于某道题的分数'},
        ),
    ]
