# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='动态生成的更改信息的链接后缀')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], max_length=10, verbose_name='状态字符串')),
            ],
            options={
                'verbose_name_plural': '给邮箱发链接(忘记密码)所用信息',
            },
        ),
    ]
