# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ex', '0003_remove_emailverifyrecord_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], default='forget', max_length=10, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
