# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ex', '0004_emailverifyrecord_send_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='send_type',
        ),
    ]
