# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_ex', '0005_remove_emailverifyrecord_send_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='valid_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='验证建立时间'),
        ),
    ]
