# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-28 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20, verbose_name='队名')),
                ('peo_num', models.CharField(default=1, max_length=20, verbose_name='人数')),
                ('sub_num', models.IntegerField(default=0, verbose_name='提交次数')),
                ('max_score', models.IntegerField(default=0, verbose_name='最高分')),
                ('last_score', models.IntegerField(default=0, verbose_name='最新分数')),
                ('ma_sc_dat', models.DateField(default=django.utils.timezone.now, verbose_name='最高分日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('captain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, verbose_name='学号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('college', models.CharField(max_length=10, verbose_name='学校')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10, verbose_name='性别')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
