# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-14 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_or_not', models.BooleanField(default=False, verbose_name='是否验证过身份')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '修改个人信息时的身份验证',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20, verbose_name='队名')),
                ('peo_num', models.IntegerField(default=1, verbose_name='人数')),
                ('sub_num', models.IntegerField(default=0, verbose_name='提交次数')),
                ('max_score', models.FloatField(default=0, verbose_name='最高分')),
                ('captain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '队伍',
                'ordering': ['-max_score'],
            },
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.BooleanField(verbose_name='是否由队伍发出')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
            ],
            options={
                'verbose_name_plural': '组队请求',
            },
        ),
        migrations.CreateModel(
            name='UserCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
            ],
            options={
                'verbose_name_plural': '最终报名比赛个人信息',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, verbose_name='学号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('college', models.CharField(max_length=10, verbose_name='学校')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.AddField(
            model_name='usercompetition',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
