# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.BooleanField(verbose_name='1：队伍发出,0：参赛者发出')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否被删除')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Team'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
