# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190129_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '队伍'},
        ),
        migrations.AlterModelOptions(
            name='teamrequest',
            options={'verbose_name_plural': '组队请求'},
        ),
        migrations.AlterField(
            model_name='teamrequest',
            name='tag',
            field=models.BooleanField(verbose_name='是否由队伍发出'),
        ),
    ]
