# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190129_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '最终报名比赛个人信息',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='teamrequest',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
        migrations.AddField(
            model_name='usercompetition',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team'),
        ),
        migrations.AddField(
            model_name='usercompetition',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
