# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190129_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-max_score'], 'verbose_name_plural': '队伍'},
        ),
    ]
