# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190129_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Team'),
        ),
    ]
