# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-31 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190130_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
