# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190131_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='peo_num',
            field=models.IntegerField(default=1, max_length=20, verbose_name='人数'),
        ),
    ]
