# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-16 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190216_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirm',
            options={'verbose_name_plural': '修改个人信息时的身份验证'},
        ),
    ]
