# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-05 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190305_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='last_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ma_sc_dat',
        ),
    ]
